name: Laravel Deploy

on:
  push:
    branches:
      - salah    # الفرع اللي تشتغل عليه (انت كنت على "salah")

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/veroanalysis/public_html/system.veroanalysis.com
            git stash
            git pull origin salah
            /usr/bin/php /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
            /usr/bin/php artisan optimize:clear
            chmod -R 775 storage
            chmod -R 775 bootstrap/cache
            chmod 777 -R storage/framework/*
            /usr/bin/php artisan migrate --force
            /usr/bin/php artisan storage:link
            npm install
            npm run production
            /usr/bin/php artisan run:sql
            sudo /usr/sbin/service supervisor restart
